# Generated by Django 5.0.2 on 2024-03-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_billing_gst"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="inv_date",
            field=models.DateField(null=True),
        ),
    ]
