# Generated by Django 5.0.2 on 2024-03-23 06:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_billing_inv_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billing",
            name="truck",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
