# Generated by Django 5.0.2 on 2024-03-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_billing_truck"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="c_date",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
