# Generated by Django 5.0.2 on 2024-03-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_billing_c_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="lr_no",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
