# Generated by Django 5.0.2 on 2024-03-23 12:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_billing_lr_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="lr_no",
        ),
    ]
