# Generated by Django 5.0.2 on 2024-03-23 13:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_remove_billing_lr_no"),
    ]

    operations = [
        migrations.RenameField(
            model_name="billing",
            old_name="invoice_number",
            new_name="c_inv_no",
        ),
    ]
