# Generated by Django 5.0.2 on 2024-03-23 13:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_rename_invoice_number_billing_c_inv_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="billing",
            name="Lr_no",
        ),
    ]
