# Generated by Django 5.0.2 on 2024-03-23 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0009_remove_billing_lr_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="billing",
            name="Lr_no",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
